const convertDataRada = (response: any) => {
    const result = response.map((item, index) => {
        return {
            0: item.companyName,
            1: item.overalScore,
            2: item?.itemCategory,
            3: item?.itemName,
            4: item?.achivements,
            5: item?.businessTypeCode,
            6: '123456',
            7: '日本，東京',
            8: '鉄鋼製造業',
            9: item.locationArea,
            10: item.headquartersLocation,
            11: Math.round(item?.capital / 1000000),
            12: item.businessName,
            13: '',
            14: '製品３',
            15: item.regularCustomer,
            16: item.establishmentYear,
            17: item.numberOfEmployees,
            18: item.representative,
            19: Math.round(item?.sales / 1000000),
            20: '101.0 ',
            21: item.capitalRatio,
            22: item.updateDate,
            23: item.updateYear,
            24: '',
            25: '鋳造炉',
            26: '',
            27: '',
            28: '5軸M/C ，鋳造炉	',
            29: '1856社中',
            30: '〇',
            31: '〇',
            32: item.qualityScore,
            33: item?.costScore,
            34: item?.deliveryScore,
            35: item?.financeScore,
            36: item?.environmentScore,
            37: item?.laborScore,
            38: item?.ethicsScore,
            39: item?.sustainableScore,
            40: '',
            41: '',
            42: item.imagePath,
            43: item.hpLink,
            44: item?.companyId,
            45: item.staffMessage,
        };
    });
    return result;
};

export { convertDataRada };
